EE_REGION = ntscu

include ${CURDIR}/Makefile.defs

EE_LIBS = -lrac1ntscu
EE_DEFS = -DRAC_NTSCU -DRAC1_NTSCU -DNTSCU -DRAC1_V100 -DRAC_V100 -DRAC1_NTSCU_V100
PNACH_NAME = SCUS-97199_CE4933D0

include ${CURDIR}/../Makefile.pref
include ${CURDIR}/../Makefile.eeglobal
