EE_REGION = ntscu

include ${CURDIR}/Makefile.defs

EE_LIBS = -lrac1ntscu
EE_DEFS = -DRAC_NTSCU -DRAC1_NTSCU -DNTSCU
PNACH_NAME = SCUS-97199_CE4933D0

include ${CURDIR}/../Makefile.pref
include ${CURDIR}/../Makefile.eeglobal
